[window]
dimensions = { columns = 120, lines = 36}
dynamic_padding = true
decorations = "Full"
title = "Good Good Study, Day Day Up!"

[font]
normal = {family = "mononoki Nerd Font", style = "Regular" }
bold = {family = "mononoki Nerd Font", style = "Bold" }
italic = {family = "mononoki Nerd Font", style = "Regular" }
bold_italic = {family = "mononoki Nerd Font", style = "Bold" }
size = 22.0
offset = { x = 2, y = 0 }

[terminal]
shell = { program = "/usr/local/bin/fish", args = ["--login"]}

